// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbP8v9--lGQXutPzlWQ1Pi3oC8ufaeNpk',
    appId: '1:264880580737:web:3e11f5e713168f20b80580',
    messagingSenderId: '264880580737',
    projectId: 'my-ecommerce-app-222-cbed5',
    authDomain: 'my-ecommerce-app-222-cbed5.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-222-cbed5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBayZPSKhs6VAPHlrAMenfd27FInxWSdNg',
    appId: '1:264880580737:android:c47864a1418ad455b80580',
    messagingSenderId: '264880580737',
    projectId: 'my-ecommerce-app-222-cbed5',
    storageBucket: 'my-ecommerce-app-222-cbed5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0pX9sVfx-sBmms-tbTR6aHN3_OMxqhM',
    appId: '1:337473087645:web:1d01891110d6936c918c74',
    messagingSenderId: '337473087645',
    projectId: 'my-ecommerce-app-down',
    authDomain: 'my-ecommerce-app-down.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-down.firebasestorage.app',
  );
}